apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-mini-app
spec:
  replicas: 2
  selector:
    matchLabels: {app: devops-mini-app}
  template:
    metadata:
      labels: {app: devops-mini-app}
    spec:
      containers:
        - name: app
          image: YOUR_ECR_REPOSITORY/devops-mini-app:IMAGE_TAG
          ports: [{containerPort: 3000}]
          readinessProbe:
            httpGet: {path: /health, port: 3000}
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet: {path: /health, port: 3000}
            initialDelaySeconds: 10
            periodSeconds: 20
          resources:
            requests: {cpu: 100m, memory: 128Mi}
            limits: {cpu: 500m, memory: 256Mi}
